using Nzr.Orm.Core.Extensions;
using Nzr.Orm.Core.Sql;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;

namespace Nzr.Orm.Core
{
    /// <summary>
    /// Partial class Dao.
    /// Contains all methods related to insert operations.
    /// </summary>
    public partial class Dao
    {
        #region Operations
        private int DoUpdate(object entity)
        {
            Set set = BuildSet(entity);
            Where where = BuildWhereFromIds(entity);

            return DoUpdate(entity.GetType(), set, where);
        }
        private int DoUpdate<T>(Set set, Where where) => DoUpdate(typeof(T), set, where);

        private int DoUpdate(Type type, Set set, Where where)
        {
            string sql = BuildUpdateSql(type, set, where);
            Parameters parameters = BuildUpdateParameters(type, set, where);
            int result = DoExecuteNonQuery(sql, parameters);

            return result;
        }

        #endregion

        #region SQL

        private string BuildUpdateSql(Type type, Set set, Where where)
        {
            IList<KeyValuePair<string, PropertyInfo>> columns = GetColumns(type);

            IList<string> setSql = set.Select(s =>
            {
                KeyValuePair<string, PropertyInfo> column = columns.First(kvp => kvp.Value.Name == s.Item1);
                StringBuilder setExpression = new StringBuilder($"{column.Key} = ");

                if (s.Item2 == null)
                {
                    setExpression.Append(" NULL");
                }
                else
                {
                    setExpression.Append($" @{FormatParameters(column.Key)}_{s.Item3}");
                }

                return setExpression.ToString();
            }).ToList();

            IList<string> whereSql = BuildWhereFilters(columns, where);
            string sql = $"UPDATE {GetTable(type)} SET {string.Join(", ", setSql)} WHERE {string.Join(" AND ", whereSql)}";

            return sql;
        }

        #endregion

        #region Parameters

        private Parameters BuildUpdateParameters(Type type, Set set, Where where)
        {
            Parameters parameters = new Parameters();
            IList<KeyValuePair<string, PropertyInfo>> columns = GetColumns(type);

            set.ForEach((parameter, value, index) =>
            {
                if (value != null)
                {
                    KeyValuePair<string, PropertyInfo> column = columns.First(c => c.Value.Name == parameter);
                    parameters.Add($"@{FormatParameters(column.Key)}_{index}", value);
                }
            });

            where.ForEach((parameter, condition, value, index) =>
            {
                if (value != null)
                {
                    KeyValuePair<string, PropertyInfo> column = columns.First(c => c.Value.Name == parameter);
                    parameters.Add($"@{FormatParameters(column.Key)}_{index}", value);
                }
            });

            return parameters;
        }

        private Set BuildSet(object entity)
        {
            Set set = new Set();
            IEnumerable<KeyValuePair<string, PropertyInfo>> nonIdentityColumns = GetNonAutoGeneratedColumns(entity.GetType());
            nonIdentityColumns.ForEach(c => set.Add(c.Value.Name, GetValue(c.Value, entity)));

            return set;
        }

        #endregion
    }
}
